In [3]:
import numpy as np

In [4]:
a=np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a[1]

np.int64(1)

In [9]:
a[1:4]

array([1, 2, 3])

In [10]:
np.__version__

'2.1.3'

In [11]:
type(a)

numpy.ndarray

In [13]:
a.dtype

dtype('int64')

In [14]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

In [15]:
type(b)

numpy.ndarray

In [16]:
b.dtype

dtype('float64')

In [17]:
c = np.array([20, 1, 2, 3, 4])

In [18]:
c[0]=100

In [19]:
c

array([100,   1,   2,   3,   4])

In [20]:
a = np.array([10, 2, 30, 40,50])


In [21]:
a[1]=20

In [22]:
a

array([10, 20, 30, 40, 50])

In [23]:
d=c[1:4]

We pass slice like this: [start:end].The element at end index is not being included in the output.

If we don't pass start its considered 0

If we don't pass end it considers till the length of array.

c[0:len(c)]  the same as c[:]

define the steps in slicing, like this: [start:end:step].


In [ ]:
c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [28]:
c[:2]

array([100,   1])

In [30]:
c[2:]

array([  2, 300, 400])

In [31]:
len(c)

5

In [34]:
c[0:len(c)]

array([100,   1,   2, 300, 400])

In [35]:
c[:]

array([100,   1,   2, 300, 400])

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr[1::2]

array([2, 4, 6, 8])

In [39]:
select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [40]:
c[select]

array([100,   2, 300, 400])

In [41]:
c

array([100,   1,   2, 300, 400])

In [42]:
c.size

5

In [43]:
c.ndim

1

In [44]:
c.shape

(5,)

In [49]:
a = np.array([1, -1, 1, -1,10])
a

array([ 1, -1,  1, -1, 10])

In [50]:
a.mean()

np.float64(2.0)

In [51]:
a.std()

np.float64(4.09878030638384)

In [52]:
a.max()

np.int64(10)

In [53]:
a.min()

np.int64(-1)