In [1]:
import numpy as np


In [2]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
A.ndim

2

In [5]:
A.shape

(3, 3)

In [6]:
A.size

9

In [7]:
A[1,2]

np.int64(23)

In [8]:
A[1][2]

np.int64(23)

In [9]:
A[0,0]

np.int64(11)

In [10]:
A[0][0:2]

array([11, 12])

In [11]:
A[0:2,2]

array([13, 23])

In [12]:
A[0:2,1:2]

array([[12],
       [22]])

In [13]:
X = np.array([[1, 0], [0, 1]]) 
Y = np.array([[2, 1], [1, 2]])

In [15]:
X+Y

array([[3, 1],
       [1, 3]])

In [16]:
X*Y

array([[2, 0],
       [0, 2]])

In [17]:
np.dot(X,Y)

array([[2, 1],
       [1, 2]])

In [18]:
X.T

array([[1, 0],
       [0, 1]])

In [19]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [20]:
a

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [24]:
A=np.array(a)

In [26]:
A.size

12

In [29]:
A[0,0:2]

array([1, 2])

In [30]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

In [32]:
np.dot(A,B)

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])